using nilnul.characters_;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.lang.grammar_.contextual_.contextless_.regular
{
	/// <summary>
	/// All languages generated by a regular grammar can be recognized in  O(n) time by a finite-state machine. 
	/// </summary>
	///  some forms of regular expression used in practice do not strictly generate the regular languages and do not show linear recognitional performance due to those deviations.
	internal class Recognize
	{
	}
}
