using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.lang._compile
{
	///en.wikipedia.org/wiki/Linker_(computing)
	///
	/// <summary>
	/// For most compilers, each object file is the result of compiling one input source code file. 
	/// </summary>
	/// <remarks>
	///takes one or more object files (generated by a compiler or an assembler) and combines them into a single executable file, library file, or another "object" file.
	/// lib + objs => lib|dll|exe
	/// </remarks>
	/// 
	internal class ILink
	{
	}
}
