namespace nilnul.lang.grammar.symbol
{
	///en.wikipedia.org/wiki/Normal_form_(abstract_rewriting)#Definition
	///
	/// <summary>
	/// the (distinct sequence)s generated by recursively deduce.
	/// at least one seq can be generated each if it's <see cref="be_.IUnDeducible"/> when it's the empty sequence.
	///
	/// the sequence can be cyclic.
	/// the sequence can be infinite, monotonically increasing, or swirling back shorter sporadically.
	/// </summary>
	/// <remarks>
	/// this forms an finite or infinite <see cref="nilnul.ral_.IDac"/>
	/// note:
	///		a symbol may be by different algorithms to reduce, resulting in different sequences. For our definition, we enumerate the next step of each <see cref="IDeduce"/>, before moving on to next step. Hence, as long as there is one sequences that is infinite, the resulted sequences is infinite. But an undeducible symbol might appear in the middle, or a subsequence that is <see cref="deduce.relay_.ICyclic"/>
	/// </remarks>
	public interface IReduce
		:nilnul.obj.seq_.IDistinct
    {

    }

}
